# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["mandy@cpan.org"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-empty"
description = "Easier than reading the headers!"
language = "javascript"
manifest_version = 3
name = "cache-visualiser"
service_id = ""

[local_server]

[scripts]
  build = "npm run build"
  post_init = "npm install"
